
#include "Bundle_Play.h"
Bundle_Play* gBundle_Play=NULL;

void Bundle_Play::Load()
{
	OverrideTextureSize();
	if (IsRetina("Play")) {if (!SpriteBundle::Load("Play@2X")) return;LoadData("Play@2X");}
	else {if (!SpriteBundle::Load("Play")) return;LoadData("Play");}
	
	// Begin Bundler Automatic Code
	int aSCount=0;
	m1up.BundleLoad(0,mTextureList,*mData);
	mAcid.BundleLoad(0,mTextureList,*mData);
	mAcidDamage.BundleLoad(0,mTextureList,*mData);
	mAciddot.BundleLoad(0,mTextureList,*mData);
	mAcidglow.BundleLoad(0,mTextureList,*mData);
	mBack.BundleLoad(0,mTextureList,*mData);
	mBlueguy_Pupile.BundleLoad(0,mTextureList,*mData);
	mBoltglow.BundleLoad(0,mTextureList,*mData);
	mBoss.BundleLoad(0,mTextureList,*mData);
	mBrickfragment.BundleLoad(0,mTextureList,*mData);
	mCancel.BundleLoad(0,mTextureList,*mData);
	mClosecomment.BundleLoad(0,mTextureList,*mData);
	mCloseFilter.BundleLoad(0,mTextureList,*mData);
	mComputer.BundleLoad(0,mTextureList,*mData);
	mComputer_Happy.BundleLoad(0,mTextureList,*mData);
	mComputer_Happy_Blink.BundleLoad(0,mTextureList,*mData);
	mComputer_Sad.BundleLoad(0,mTextureList,*mData);
	mComputer_Sad_Blink.BundleLoad(0,mTextureList,*mData);
	mComputron.BundleLoad(0,mTextureList,*mData);
	mComputron_Activated.BundleLoad(0,mTextureList,*mData);
	mComputron_Blink.BundleLoad(0,mTextureList,*mData);
	mComputron_Eye.BundleLoad(0,mTextureList,*mData);
	mComputron_Glint.BundleLoad(0,mTextureList,*mData);
	mComputron_Glintwhite.BundleLoad(0,mTextureList,*mData);
	mControl_Jump.BundleLoad(0,mTextureList,*mData);
	mControl_Move.BundleLoad(0,mTextureList,*mData);
	mControl_Rocket.BundleLoad(0,mTextureList,*mData);
	mControl_Rocketup.BundleLoad(0,mTextureList,*mData);
	mControl_Shoot.BundleLoad(0,mTextureList,*mData);
	mDeleteads.BundleLoad(0,mTextureList,*mData);
	mDeletetimers.BundleLoad(0,mTextureList,*mData);
	mDialogRim.BundleLoad(0,mTextureList,*mData);
	mDripboss_Pupil.BundleLoad(0,mTextureList,*mData);
	mDust.BundleLoad(0,mTextureList,*mData);
	mEditCursor.BundleLoad(0,mTextureList,*mData);
	mEngineglow.BundleLoad(0,mTextureList,*mData);
	mExplode.BundleLoad(0,mTextureList,*mData);
	mExplode1.BundleLoad(0,mTextureList,*mData);
	mExplode2.BundleLoad(0,mTextureList,*mData);
	mFlashLevelUp.BundleLoad(0,mTextureList,*mData);
	mFloaty.BundleLoad(0,mTextureList,*mData);
	mGlow.BundleLoad(0,mTextureList,*mData);
	mGlowy_No.BundleLoad(0,mTextureList,*mData);
	mGlowy_Ok.BundleLoad(0,mTextureList,*mData);
	mGlowy_Yes.BundleLoad(0,mTextureList,*mData);
	mGreenGuy_Arm.BundleLoad(0,mTextureList,*mData);
	mGreenGuy_Body.BundleLoad(0,mTextureList,*mData);
	mGreenGuy_Feelers.BundleLoad(0,mTextureList,*mData);
	mGreenGuy_Hole.BundleLoad(0,mTextureList,*mData);
	mGreenGuy_Shell.BundleLoad(0,mTextureList,*mData);
	mGunTarget.BundleLoad(0,mTextureList,*mData);
	mGuntargeticon.BundleLoad(0,mTextureList,*mData);
	mHaxxor.BundleLoad(0,mTextureList,*mData);
	mHaxxormask.BundleLoad(0,mTextureList,*mData);
	mHeart_Empty.BundleLoad(0,mTextureList,*mData);
	mHeart_Full.BundleLoad(0,mTextureList,*mData);
	mHelpus.BundleLoad(0,mTextureList,*mData);
	mJumpburst.BundleLoad(0,mTextureList,*mData);
	mKitty.BundleLoad(0,mTextureList,*mData);
	mKitty_Blink.BundleLoad(0,mTextureList,*mData);
	mKittyship.BundleLoad(0,mTextureList,*mData);
	mLandpoof.BundleLoad(0,mTextureList,*mData);
	mLazor.BundleLoad(0,mTextureList,*mData);
	mLazorglint.BundleLoad(0,mTextureList,*mData);
	mLevelup.BundleLoad(0,mTextureList,*mData);
	mLifter.BundleLoad(0,mTextureList,*mData);
	mLoading.BundleLoad(0,mTextureList,*mData);
	mLogin_Txt.BundleLoad(0,mTextureList,*mData);
	mLogout_Gfx.BundleLoad(0,mTextureList,*mData);
	mLogout_Txt.BundleLoad(0,mTextureList,*mData);
	mLong_Cancel.BundleLoad(0,mTextureList,*mData);
	mLong_OK.BundleLoad(0,mTextureList,*mData);
	mMakerMall.BundleLoad(0,mTextureList,*mData);
	mMap_Ingame.BundleLoad(0,mTextureList,*mData);
	mMenubutton.BundleLoad(0,mTextureList,*mData);
	mMM_Bar.BundleLoad(0,mTextureList,*mData);
	mMM_Comment.BundleLoad(0,mTextureList,*mData);
	mMm_Edit.BundleLoad(0,mTextureList,*mData);
	mMM_Header.BundleLoad(0,mTextureList,*mData);
	mMM_Heart.BundleLoad(0,mTextureList,*mData);
	mMM_HotLevels.BundleLoad(0,mTextureList,*mData);
	mMM_HotLevels_Small.BundleLoad(0,mTextureList,*mData);
	mMM_MyLevels.BundleLoad(0,mTextureList,*mData);
	mMM_NewLevels.BundleLoad(0,mTextureList,*mData);
	mMM_NewLevels_Small.BundleLoad(0,mTextureList,*mData);
	mMm_Pencil.BundleLoad(0,mTextureList,*mData);
	mMM_Playing.BundleLoad(0,mTextureList,*mData);
	mMM_Random.BundleLoad(0,mTextureList,*mData);
	mMM_Search.BundleLoad(0,mTextureList,*mData);
	mMM_Star.BundleLoad(0,mTextureList,*mData);
	mMM_Starred.BundleLoad(0,mTextureList,*mData);
	mMM_Tags.BundleLoad(0,mTextureList,*mData);
	mMMnoads.BundleLoad(0,mTextureList,*mData);
	mNo.BundleLoad(0,mTextureList,*mData);
	mOK.BundleLoad(0,mTextureList,*mData);
	mOuchburst.BundleLoad(0,mTextureList,*mData);
	mOuchstar.BundleLoad(0,mTextureList,*mData);
	mPickerComputer.BundleLoad(0,mTextureList,*mData);
	mPixel.BundleLoad(0,mTextureList,*mData);
	mPixel_Glow.BundleLoad(0,mTextureList,*mData);
	mPlay.BundleLoad(0,mTextureList,*mData);
	mQuit_Ingame.BundleLoad(0,mTextureList,*mData);
	mRadio.BundleLoad(0,mTextureList,*mData);
	mRate_Border.BundleLoad(0,mTextureList,*mData);
	mRate_Comment.BundleLoad(0,mTextureList,*mData);
	mRate_Done.BundleLoad(0,mTextureList,*mData);
	mRate_ExtraLove.BundleLoad(0,mTextureList,*mData);
	mRate_Greystar.BundleLoad(0,mTextureList,*mData);
	mRate_Hilitecircle.BundleLoad(0,mTextureList,*mData);
	mRate_Hilitereport.BundleLoad(0,mTextureList,*mData);
	mRate_Hilitestar.BundleLoad(0,mTextureList,*mData);
	mRate_Like.BundleLoad(0,mTextureList,*mData);
	mRate_Nostars.BundleLoad(0,mTextureList,*mData);
	mRate_Report.BundleLoad(0,mTextureList,*mData);
	mRate_ReportAbuse.BundleLoad(0,mTextureList,*mData);
	mRate_Star.BundleLoad(0,mTextureList,*mData);
	mResetLevel.BundleLoad(0,mTextureList,*mData);
	mRestart_Ingame.BundleLoad(0,mTextureList,*mData);
	mResume_Ingame.BundleLoad(0,mTextureList,*mData);
	mRobot_Idle.BundleLoad(0,mTextureList,*mData);
	mRobot_Idle_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Idleshoot.BundleLoad(0,mTextureList,*mData);
	mRobot_Idleshoot_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Jump.BundleLoad(0,mTextureList,*mData);
	mRobot_Jump_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Jumpshoot.BundleLoad(0,mTextureList,*mData);
	mRobot_Jumpshoot_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Rocket.BundleLoad(0,mTextureList,*mData);
	mRobot_Rocket_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Rocketup.BundleLoad(0,mTextureList,*mData);
	mRobot_Rocketup_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Run.BundleLoad(0,mTextureList,*mData);
	mRobot_Run_Helmet.BundleLoad(0,mTextureList,*mData);
	mRobot_Runwheel.BundleLoad(0,mTextureList,*mData);
	mRocketfire.BundleLoad(0,mTextureList,*mData);
	mRocketfireup.BundleLoad(0,mTextureList,*mData);
	mRWK.BundleLoad(0,mTextureList,*mData);
	mSayit.BundleLoad(0,mTextureList,*mData);
	mScreenshot.BundleLoad(0,mTextureList,*mData);
	mScrollcaret.BundleLoad(0,mTextureList,*mData);
	mSetup.BundleLoad(0,mTextureList,*mData);
	mSetup_Ingame.BundleLoad(0,mTextureList,*mData);
	mSliderthumb.BundleLoad(0,mTextureList,*mData);
	mSmallrim.BundleLoad(0,mTextureList,*mData);
	mSmoke.BundleLoad(0,mTextureList,*mData);
	mSplodefragment.BundleLoad(0,mTextureList,*mData);
	mSwipeformore.BundleLoad(0,mTextureList,*mData);
	mTeenyCorner.BundleLoad(0,mTextureList,*mData);
	mTelelight.BundleLoad(0,mTextureList,*mData);
	mTelematic.BundleLoad(0,mTextureList,*mData);
	mTelematic_Blink.BundleLoad(0,mTextureList,*mData);
	mTelematic_Off.BundleLoad(0,mTextureList,*mData);
	mTelematic_On.BundleLoad(0,mTextureList,*mData);
	mTelematic_Slot.BundleLoad(0,mTextureList,*mData);
	mTelematiclight.BundleLoad(0,mTextureList,*mData);
	mTinyCorner.BundleLoad(0,mTextureList,*mData);
	mTrash.BundleLoad(0,mTextureList,*mData);
	mVolume_Gfx.BundleLoad(0,mTextureList,*mData);
	mWhiteheart.BundleLoad(0,mTextureList,*mData);
	mWin.BundleLoad(0,mTextureList,*mData);
	mWireless.BundleLoad(0,mTextureList,*mData);
	mYes.BundleLoad(0,mTextureList,*mData);
	mYougotmail.BundleLoad(0,mTextureList,*mData);
	mYourKarma.BundleLoad(0,mTextureList,*mData);
	mYourStars.BundleLoad(0,mTextureList,*mData);
	mYourStarsTop.BundleLoad(0,mTextureList,*mData);
	mFillrect.BundleLoad(0,mTextureList,*mData);

	mBlueguy.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mBlueguy[aSCount].BundleLoad(0,mTextureList,*mData);
	mBlueguy1.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mBlueguy1[aSCount].BundleLoad(0,mTextureList,*mData);
	mBlueguy2.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mBlueguy2[aSCount].BundleLoad(0,mTextureList,*mData);
	mBlueguy3.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mBlueguy3[aSCount].BundleLoad(0,mTextureList,*mData);
	mBlueguy_Blink.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mBlueguy_Blink[aSCount].BundleLoad(0,mTextureList,*mData);
	mBoss0.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mBoss0[aSCount].BundleLoad(0,mTextureList,*mData);
	mBoss1.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mBoss1[aSCount].BundleLoad(0,mTextureList,*mData);
	mBoss2.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mBoss2[aSCount].BundleLoad(0,mTextureList,*mData);
	mBoss3.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mBoss3[aSCount].BundleLoad(0,mTextureList,*mData);
	mBoss_Mouth.GuaranteeSize(3);for (aSCount=0;aSCount<3;aSCount++) mBoss_Mouth[aSCount].BundleLoad(0,mTextureList,*mData);
	mBubble.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mBubble[aSCount].BundleLoad(0,mTextureList,*mData);
	mBuzzoid.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mBuzzoid[aSCount].BundleLoad(0,mTextureList,*mData);
	mBuzzoid1.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mBuzzoid1[aSCount].BundleLoad(0,mTextureList,*mData);
	mBuzzoid2.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mBuzzoid2[aSCount].BundleLoad(0,mTextureList,*mData);
	mBuzzoid3.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mBuzzoid3[aSCount].BundleLoad(0,mTextureList,*mData);
	mCheckbox.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mCheckbox[aSCount].BundleLoad(0,mTextureList,*mData);
	mCoin.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mCoin[aSCount].BundleLoad(0,mTextureList,*mData);
	mCrack.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mCrack[aSCount].BundleLoad(0,mTextureList,*mData);
	mDrip.GuaranteeSize(5);for (aSCount=0;aSCount<5;aSCount++) mDrip[aSCount].BundleLoad(0,mTextureList,*mData);
	mDrip1.GuaranteeSize(5);for (aSCount=0;aSCount<5;aSCount++) mDrip1[aSCount].BundleLoad(0,mTextureList,*mData);
	mDrip2.GuaranteeSize(5);for (aSCount=0;aSCount<5;aSCount++) mDrip2[aSCount].BundleLoad(0,mTextureList,*mData);
	mDrip3.GuaranteeSize(5);for (aSCount=0;aSCount<5;aSCount++) mDrip3[aSCount].BundleLoad(0,mTextureList,*mData);
	mDripboss.GuaranteeSize(10);for (aSCount=0;aSCount<10;aSCount++) mDripboss[aSCount].BundleLoad(0,mTextureList,*mData);
	mDripboss1.GuaranteeSize(10);for (aSCount=0;aSCount<10;aSCount++) mDripboss1[aSCount].BundleLoad(0,mTextureList,*mData);
	mDripboss2.GuaranteeSize(10);for (aSCount=0;aSCount<10;aSCount++) mDripboss2[aSCount].BundleLoad(0,mTextureList,*mData);
	mDripboss3.GuaranteeSize(10);for (aSCount=0;aSCount<10;aSCount++) mDripboss3[aSCount].BundleLoad(0,mTextureList,*mData);
	mDripbosseye.GuaranteeSize(7);for (aSCount=0;aSCount<7;aSCount++) mDripbosseye[aSCount].BundleLoad(0,mTextureList,*mData);
	mExplozor.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mExplozor[aSCount].BundleLoad(0,mTextureList,*mData);
	mFlag.GuaranteeSize(248);for (aSCount=0;aSCount<248;aSCount++) mFlag[aSCount].BundleLoad(0,mTextureList,*mData);
	mKitty_Tail.GuaranteeSize(3);for (aSCount=0;aSCount<3;aSCount++) mKitty_Tail[aSCount].BundleLoad(0,mTextureList,*mData);
	mLevelIcon.GuaranteeSize(11);for (aSCount=0;aSCount<11;aSCount++) mLevelIcon[aSCount].BundleLoad(0,mTextureList,*mData);
	mLever.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mLever[aSCount].BundleLoad(0,mTextureList,*mData);
	mNews.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mNews[aSCount].BundleLoad(0,mTextureList,*mData);
	mPhage.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mPhage[aSCount].BundleLoad(0,mTextureList,*mData);
	mQuickAd.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mQuickAd[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedboss.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mRedboss[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedboss1.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mRedboss1[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedboss2.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mRedboss2[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedboss3.GuaranteeSize(8);for (aSCount=0;aSCount<8;aSCount++) mRedboss3[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedguy.GuaranteeSize(6);for (aSCount=0;aSCount<6;aSCount++) mRedguy[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedguy1.GuaranteeSize(6);for (aSCount=0;aSCount<6;aSCount++) mRedguy1[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedguy2.GuaranteeSize(6);for (aSCount=0;aSCount<6;aSCount++) mRedguy2[aSCount].BundleLoad(0,mTextureList,*mData);
	mRedguy3.GuaranteeSize(6);for (aSCount=0;aSCount<6;aSCount++) mRedguy3[aSCount].BundleLoad(0,mTextureList,*mData);
	mRobits.GuaranteeSize(6);for (aSCount=0;aSCount<6;aSCount++) mRobits[aSCount].BundleLoad(0,mTextureList,*mData);
	mSplash.GuaranteeSize(2);for (aSCount=0;aSCount<2;aSCount++) mSplash[aSCount].BundleLoad(0,mTextureList,*mData);
	mSwear.GuaranteeSize(15);for (aSCount=0;aSCount<15;aSCount++) mSwear[aSCount].BundleLoad(0,mTextureList,*mData);
	mTelepad_Off.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mTelepad_Off[aSCount].BundleLoad(0,mTextureList,*mData);
	mTelepad_On.GuaranteeSize(4);for (aSCount=0;aSCount<4;aSCount++) mTelepad_On[aSCount].BundleLoad(0,mTextureList,*mData);
	mFont_Tiny.BundleLoad(0,mTextureList,*mData);
	mFont_Tiny_Outline.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled8.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled11OutlineHard.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled11.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled18.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled8Outline.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled11Outline.BundleLoad(0,mTextureList,*mData);
	mFont_Commodore64Angled18Outline.BundleLoad(0,mTextureList,*mData);
	// End Bundler Automatic Code

	gG.RegisterFillrect(&mFillrect);
	UnloadData();
}

