//
// Auto-generated by Rapt Bundler...
//
#include "Bundle_Sounds.h"
#include "MyApp.h"

Bundle_Sounds *gSounds=NULL;
void Bundle_Sounds::Load(String theStatus)
{
gAppPtr->mLoader->Add(&mClick,"sounds://click")->AddDesc(theStatus);mSoundList+=&mClick;
gAppPtr->mLoader->Add(&mAlert,"sounds://alert")->AddDesc(theStatus);mSoundList+=&mAlert;
gAppPtr->mLoader->Add(&mAlienhit,"sounds://alienhit")->AddDesc(theStatus);mSoundList+=&mAlienhit;
gAppPtr->mLoader->Add(&mBell,"sounds://bell")->AddDesc(theStatus);mSoundList+=&mBell;
gAppPtr->mLoader->Add(&mBoom,"sounds://boom")->AddDesc(theStatus);mSoundList+=&mBoom;
gAppPtr->mLoader->Add(&mBossshoot,"sounds://bossshoot")->AddDesc(theStatus);mSoundList+=&mBossshoot;
gAppPtr->mLoader->Add(&mComputerdoor,"sounds://computerdoor")->AddDesc(theStatus);mSoundList+=&mComputerdoor;
gAppPtr->mLoader->Add(&mComputron,"sounds://computron")->AddDesc(theStatus);mSoundList+=&mComputron;
gAppPtr->mLoader->Add(&mCritterscreech,"sounds://critterscreech")->AddDesc(theStatus);mSoundList+=&mCritterscreech;
gAppPtr->mLoader->Add(&mCrumble,"sounds://crumble")->AddDesc(theStatus);mSoundList+=&mCrumble;
gAppPtr->mLoader->Add(&mCrystal,"sounds://crystal")->AddDesc(theStatus);mSoundList+=&mCrystal;
gAppPtr->mLoader->Add(&mDie,"sounds://die")->AddDesc(theStatus);mSoundList+=&mDie;
gAppPtr->mLoader->Add(&mDrip,"sounds://drip")->AddDesc(theStatus);mSoundList+=&mDrip;
gAppPtr->mLoader->Add(&mDriphelm,"sounds://driphelm")->AddDesc(theStatus);mSoundList+=&mDriphelm;
gAppPtr->mLoader->Add(&mEvaporate,"sounds://evaporate")->AddDesc(theStatus);mSoundList+=&mEvaporate;
gAppPtr->mLoader->Add(&mExplodecrate,"sounds://explodecrate")->AddDesc(theStatus);mSoundList+=&mExplodecrate;
gAppPtr->mLoader->Add(&mGooped,"sounds://gooped")->AddDesc(theStatus);mSoundList+=&mGooped;
gAppPtr->mLoader->Add(&mGotcoin,"sounds://gotcoin")->AddDesc(theStatus);mSoundList+=&mGotcoin;
gAppPtr->mLoader->Add(&mHappycomputer,"sounds://happycomputer")->AddDesc(theStatus);mSoundList+=&mHappycomputer;
gAppPtr->mLoader->Add(&mHit_Helmet,"sounds://hit_helmet")->AddDesc(theStatus);mSoundList+=&mHit_Helmet;
gAppPtr->mLoader->Add(&mJump,"sounds://jump")->AddDesc(theStatus);mSoundList+=&mJump;
gAppPtr->mLoader->Add(&mKillboss,"sounds://killboss")->AddDesc(theStatus);mSoundList+=&mKillboss;
gAppPtr->mLoader->Add(&mLaser,"sounds://laser")->AddDesc(theStatus);mSoundList+=&mLaser;
gAppPtr->mLoader->Add(&mLaserhit,"sounds://laserhit")->AddDesc(theStatus);mSoundList+=&mLaserhit;
gAppPtr->mLoader->Add(&mLaserouch,"sounds://laserouch")->AddDesc(theStatus);mSoundList+=&mLaserouch;
gAppPtr->mLoader->Add(&mMenu,"sounds://menu")->AddDesc(theStatus);mSoundList+=&mMenu;
gAppPtr->mLoader->Add(&mMeow,"sounds://meow")->AddDesc(theStatus);mSoundList+=&mMeow;
gAppPtr->mLoader->Add(&mModem,"sounds://modem")->AddDesc(theStatus);mSoundList+=&mModem;
gAppPtr->mLoader->Add(&mNomorekitty,"sounds://nomorekitty")->AddDesc(theStatus);mSoundList+=&mNomorekitty;
gAppPtr->mLoader->Add(&mOpendoor,"sounds://opendoor")->AddDesc(theStatus);mSoundList+=&mOpendoor;
gAppPtr->mLoader->Add(&mPhageNibble,"sounds://PhageNibble")->AddDesc(theStatus);mSoundList+=&mPhageNibble;
gAppPtr->mLoader->Add(&mPhageStop,"sounds://PhageStop")->AddDesc(theStatus);mSoundList+=&mPhageStop;
gAppPtr->mLoader->Add(&mPlink,"sounds://Plink")->AddDesc(theStatus);mSoundList+=&mPlink;
gAppPtr->mLoader->Add(&mPlop,"sounds://plop")->AddDesc(theStatus);mSoundList+=&mPlop;
gAppPtr->mLoader->Add(&mPowerup,"sounds://powerup")->AddDesc(theStatus);mSoundList+=&mPowerup;
gAppPtr->mLoader->Add(&mRadio,"sounds://radio")->AddDesc(theStatus);mSoundList+=&mRadio;
gAppPtr->mLoader->Add(&mRedpop,"sounds://redpop")->AddDesc(theStatus);mSoundList+=&mRedpop;
gAppPtr->mLoader->Add(&mRedpop_Emerge,"sounds://redpop_emerge")->AddDesc(theStatus);mSoundList+=&mRedpop_Emerge;
gAppPtr->mLoader->Add(&mRobotouch,"sounds://robotouch")->AddDesc(theStatus);mSoundList+=&mRobotouch;
gAppPtr->mLoader->Add(&mRocket,"sounds://rocket")->AddDesc(theStatus);mSoundList+=&mRocket;
gAppPtr->mLoader->Add(&mSelect,"sounds://select")->AddDesc(theStatus);mSoundList+=&mSelect;
gAppPtr->mLoader->Add(&mSwitch,"sounds://switch")->AddDesc(theStatus);mSoundList+=&mSwitch;
gAppPtr->mLoader->Add(&mTelematicon,"sounds://telematicon")->AddDesc(theStatus);mSoundList+=&mTelematicon;
gAppPtr->mLoader->Add(&mTeleport,"sounds://teleport")->AddDesc(theStatus);mSoundList+=&mTeleport;
gAppPtr->mLoader->Add(&mTelesizzle,"sounds://telesizzle")->AddDesc(theStatus);mSoundList+=&mTelesizzle;
gAppPtr->mLoader->Add(&mVelcro,"sounds://velcro")->AddDesc(theStatus);mSoundList+=&mVelcro;
gAppPtr->mLoader->Add(&mWake,"sounds://wake")->AddDesc(theStatus);mSoundList+=&mWake;
gAppPtr->mLoader->Add(&mWin,"sounds://win")->AddDesc(theStatus);mSoundList+=&mWin;
gAppPtr->mLoader->Add(&mZoing,"sounds://zoing")->AddDesc(theStatus);mSoundList+=&mZoing;

gAppPtr->mLoader->Add(&mStream_Music_Eraser,"sounds://music_eraser__STREAM")->AddDesc(theStatus);
gAppPtr->mLoader->Add(&mStream_Music_Gameplay1,"sounds://music_gameplay1__STREAM")->AddDesc(theStatus);
gAppPtr->mLoader->Add(&mStream_Music_Gameplay2,"sounds://music_gameplay2__STREAM")->AddDesc(theStatus);
gAppPtr->mLoader->Add(&mStream_Music_Gameplay3,"sounds://music_gameplay3__STREAM")->AddDesc(theStatus);
gAppPtr->mLoader->Add(&mStream_Music_Title,"sounds://music_title__STREAM")->AddDesc(theStatus);
gAppPtr->mLoader->Add(&mStream_Youcanlevelup,"sounds://youcanlevelup__STREAM")->AddDesc(theStatus);

gAppPtr->mLoader->Add(&mLoop_Hiss,"sounds://hiss__LOOP")->AddDesc(theStatus);mSoundList+=&mLoop_Hiss.mSound;
gAppPtr->mLoader->Add(&mLoop_Reportabuse,"sounds://reportabuse__LOOP")->AddDesc(theStatus);mSoundList+=&mLoop_Reportabuse.mSound;
gAppPtr->mLoader->Add(&mLoop_Throb,"sounds://throb__LOOP")->AddDesc(theStatus);mSoundList+=&mLoop_Throb.mSound;

gAppPtr->mLoader->Add(&mBubble[0],"sounds://bubble/bubble1")->AddDesc(theStatus);mSoundList+=&mBubble[0];
gAppPtr->mLoader->Add(&mBubble[1],"sounds://bubble/bubble2")->AddDesc(theStatus);mSoundList+=&mBubble[1];

}

void Bundle_Sounds::Stop()
{
EnumList(Sound,aSound,mSoundList) aSound->Stop();
mStream_Music_Eraser.Stop();
mStream_Music_Gameplay1.Stop();
mStream_Music_Gameplay2.Stop();
mStream_Music_Gameplay3.Stop();
mStream_Music_Title.Stop();
mStream_Youcanlevelup.Stop();

}
void Bundle_Sounds::SetVolume(float theValue)
{
EnumList(Sound,aS,mSoundList) aS->SetClipVolume(theValue);
}
/*
mClick.Stop();
mAlert.Stop();
mAlienhit.Stop();
mBell.Stop();
mBoom.Stop();
mBossshoot.Stop();
mComputerdoor.Stop();
mComputron.Stop();
mCritterscreech.Stop();
mCrumble.Stop();
mCrystal.Stop();
mDie.Stop();
mDrip.Stop();
mDriphelm.Stop();
mEvaporate.Stop();
mExplodecrate.Stop();
mGooped.Stop();
mGotcoin.Stop();
mHappycomputer.Stop();
mHit_Helmet.Stop();
mJump.Stop();
mKillboss.Stop();
mLaser.Stop();
mLaserhit.Stop();
mLaserouch.Stop();
mMenu.Stop();
mMeow.Stop();
mModem.Stop();
mNomorekitty.Stop();
mOpendoor.Stop();
mPhageNibble.Stop();
mPhageStop.Stop();
mPlink.Stop();
mPlop.Stop();
mPowerup.Stop();
mRadio.Stop();
mRedpop.Stop();
mRedpop_Emerge.Stop();
mRobotouch.Stop();
mRocket.Stop();
mSelect.Stop();
mSwitch.Stop();
mTelematicon.Stop();
mTeleport.Stop();
mTelesizzle.Stop();
mVelcro.Stop();
mWake.Stop();
mWin.Stop();
mZoing.Stop();

mStream_Music_Eraser.Stop();
mStream_Music_Gameplay1.Stop();
mStream_Music_Gameplay2.Stop();
mStream_Music_Gameplay3.Stop();
mStream_Music_Title.Stop();
mStream_Youcanlevelup.Stop();

mLoop_Hiss.Stop();
mLoop_Reportabuse.Stop();
mLoop_Throb.Stop();

mBubble[0].Stop();
mBubble[1].Stop();

*/

