//
// Auto-generated by Rapt Bundler...
//
#pragma once
#include "rapt_audio.h"

class Bundle_Sounds;
extern Bundle_Sounds *gSounds;

class Bundle_Sounds
{
public:
Bundle_Sounds() {gSounds=this;}
void		Load(String theStatus);
void		Stop();
void		SetVolume(float theVolume=1.0f);
List		mSoundList;

public:
Sound				mClick;
Sound				mAlert;
Sound				mAlienhit;
Sound				mBell;
Sound				mBoom;
Sound				mBossshoot;
Sound				mComputerdoor;
Sound				mComputron;
Sound				mCritterscreech;
Sound				mCrumble;
Sound				mCrystal;
Sound				mDie;
Sound				mDrip;
Sound				mDriphelm;
Sound				mEvaporate;
Sound				mExplodecrate;
Sound				mGooped;
Sound				mGotcoin;
Sound				mHappycomputer;
Sound				mHit_Helmet;
Sound				mJump;
Sound				mKillboss;
Sound				mLaser;
Sound				mLaserhit;
Sound				mLaserouch;
Sound				mMenu;
Sound				mMeow;
Sound				mModem;
Sound				mNomorekitty;
Sound				mOpendoor;
Sound				mPhageNibble;
Sound				mPhageStop;
Sound				mPlink;
Sound				mPlop;
Sound				mPowerup;
Sound				mRadio;
Sound				mRedpop;
Sound				mRedpop_Emerge;
Sound				mRobotouch;
Sound				mRocket;
Sound				mSelect;
Sound				mSwitch;
Sound				mTelematicon;
Sound				mTeleport;
Sound				mTelesizzle;
Sound				mVelcro;
Sound				mWake;
Sound				mWin;
Sound				mZoing;

SoundStream			mStream_Music_Eraser;
SoundStream			mStream_Music_Gameplay1;
SoundStream			mStream_Music_Gameplay2;
SoundStream			mStream_Music_Gameplay3;
SoundStream			mStream_Music_Title;
SoundStream			mStream_Youcanlevelup;

SoundLoop			mLoop_Hiss;
SoundLoop			mLoop_Reportabuse;
SoundLoop			mLoop_Throb;

Sound				mBubble[2];
};

enum
{
SOUNDINDEX_CLICK,
SOUNDINDEX_ALERT,
SOUNDINDEX_ALIENHIT,
SOUNDINDEX_BELL,
SOUNDINDEX_BOOM,
SOUNDINDEX_BOSSSHOOT,
SOUNDINDEX_COMPUTERDOOR,
SOUNDINDEX_COMPUTRON,
SOUNDINDEX_CRITTERSCREECH,
SOUNDINDEX_CRUMBLE,
SOUNDINDEX_CRYSTAL,
SOUNDINDEX_DIE,
SOUNDINDEX_DRIP,
SOUNDINDEX_DRIPHELM,
SOUNDINDEX_EVAPORATE,
SOUNDINDEX_EXPLODECRATE,
SOUNDINDEX_GOOPED,
SOUNDINDEX_GOTCOIN,
SOUNDINDEX_HAPPYCOMPUTER,
SOUNDINDEX_HIT_HELMET,
SOUNDINDEX_JUMP,
SOUNDINDEX_KILLBOSS,
SOUNDINDEX_LASER,
SOUNDINDEX_LASERHIT,
SOUNDINDEX_LASEROUCH,
SOUNDINDEX_MENU,
SOUNDINDEX_MEOW,
SOUNDINDEX_MODEM,
SOUNDINDEX_NOMOREKITTY,
SOUNDINDEX_OPENDOOR,
SOUNDINDEX_PHAGENIBBLE,
SOUNDINDEX_PHAGESTOP,
SOUNDINDEX_PLINK,
SOUNDINDEX_PLOP,
SOUNDINDEX_POWERUP,
SOUNDINDEX_RADIO,
SOUNDINDEX_REDPOP,
SOUNDINDEX_REDPOP_EMERGE,
SOUNDINDEX_ROBOTOUCH,
SOUNDINDEX_ROCKET,
SOUNDINDEX_SELECT,
SOUNDINDEX_SWITCH,
SOUNDINDEX_TELEMATICON,
SOUNDINDEX_TELEPORT,
SOUNDINDEX_TELESIZZLE,
SOUNDINDEX_VELCRO,
SOUNDINDEX_WAKE,
SOUNDINDEX_WIN,
SOUNDINDEX_ZOING,
SOUND_MAX
};

